#!/bin/bash

# Grant the user project access.
chown user:project -R /home/user/projects
setfacl -d -m g:w /home/user/projects

# Start ttyd.
su - user -c 'ttyd -p 3000 bash' &

# Start mkdocs.
cd /home/user/projects/docs
mkdocs serve -a 127.0.0.1:8000 &
cd -

# Configure the site.
cd setup
source venv/bin/activate
python3 configure_site.py "$@"
deactivate

# Hack PHP to let 'user' run nginx rather than 'www-data'.
sed -i -e 's/www-data/user/' /etc/php/7.0/fpm/pool.d/www.conf

# Launch the site.
pip install -r requirements.txt
service php7.0-fpm start
service nginx start

# Non-end command to keep running.
tail -F /var/log/nginx/error.log
